### ISSUE TITLE
Feature Request: Prioritise fixing of placeholder prompts

### ISSUE THREAD

**Issue by UrsBeeli** [aecreations/clippings#151]
As per [https://aecreations.blogspot.ch/2017/11/known-issues-with-clippings-6.html](https://aecreations.blogspot.ch/2017/11/known-issues-with-clippings-6.html) I understand that it is planned to fix the issue of the placeholder prompt not appearing when custom placeholders are part of a clipping.

However "in a future release" is very vague and this is a feature we heavily use and the lack of it causes significant overhead when using the clippings. It would be great if fixing this issue could be given high priority and ideally letting us know when such a fix would be available would be much appreciated!

**Comment by aecreations** [comment]
Fixed in 6.0.2
