### ISSUE TITLE
BUG: Shortcut doesn't work when using two monitors

### ISSUE THREAD

**Issue by pyroexe** [aecreations/clippings#185]
Hi there, 

I've got this experience when working with the web extension. This was working when it wasn't a web extension. 

So I've got a secondary monitor with Firefox opened, then I press down the keys to use a shortcut. This dialogue window opens up in the primary monitor; I press down the shortcut in question and nothing happen. 

<img width="500" alt="shortcut" src="https://user-images.githubusercontent.com/36871930/36764758-f7a6f8d4-1c92-11e8-9220-2a076638c5e9.png">

The workaround is to move the dialogue window to the secondary screen and press down the shortcut to obtain the desired clipping. 

Cheers

**Comment by aecreations** [comment]
Thanks for reporting this. I'll see if I can repro this as well on a Windows dual-monitor setup. Looks like something that will need to be added to the list of known issues/limitations.

**Comment by pyroexe** [comment]
Thanks for looking into this issue. 

I've reproduced this on Windows 10 and Mac OS 10.12

Cheers!

**Comment by aecreations** [comment]
Fixed in version 6.3
