### ISSUE TITLE
provide a way around security barriers

### ISSUE THREAD

**Issue by narayaan** [aecreations/clippings#192]
I use clippings to enter my password on a certain site (simplified explanation, I have 22 paswords to chose from in this particular usecase). This used to work without a problem, but now there's some kind of protection against entering the password with clippings (probably an anti-bot measure). I'm able to fill in the password, but I need to change it manually in order to proceed.

For example, when adding the password "password" I will need to delete the "D" and add it again to convince that I'm human.

**Comment by aecreations** [comment]
There are no plans to defeat these anti-bot measures that some sites are now using.

For your particular use case, you may want to consider using a password manager add-on instead.
