### ISSUE TITLE
Ability to save ordering of clippings and folders in Clippings Manager

### ISSUE THREAD

**Issue by aecreations** [aecreations/clippings#202]
Clippings 6 does not allow users to be able to rearrange clippings and folders to their liking in Clippings Manager. While the Fancytree widget allows tree item rearranging by drag and drop, the rearranged tree items aren't persisted.

The reordering of clippings and folders in Clippings Manager should be persisted, and the clippings/folders should appear in the Clippings context menu in the browser in the same order as they were saved from Clippings Manager.

**Comment by aecreations** [comment]
Problem: The ordering of the Clippings context menu items doesn't get updated if the clippings/folders are reordered in Clippings Manager; I have to close and reopen Firefox for the ordering to take effect.

**Comment by aecreations** [comment]
The work on this feature is basically done. There are a few clean-up issues that need to be addressed:
#209, #210 and #211.

**Comment by pyroexe** [comment]
Just to mention that as for version 6.1.3, when importing a repository, the labels are located at the bottom after the folder, therefore the ordering is not persisted/captured when importing a previously saved repository. 

It works fine when reordering them again, the order is persisted. 

Cheers

**Comment by aecreations** [comment]
@pyroexe - I have entered a separate issue to track this request: issue #256.
