### ISSUE TITLE
Clippings Manager: Undo reordering of clippings/folders

### ISSUE THREAD

**Issue by aecreations** [aecreations/clippings#211]
Clippings 6.1a1+

Now that reordering by drag 'n drop of clippings and folders in Clippings Manager is being persisted (#202), add the ability to undo reordering.

**Comment by aecreations** [comment]
The Fancytree API has a way to add a tree node before an existing node. Method `FancytreeNode.addNode()`: 
http://www.wwwendt.de/tech/fancytree/doc/jsdoc/FancytreeNode.html#addNode

**Comment by pyroexe** [comment]
Hi there,

I think it'd be good to mention that I've been testing Clippings 6.1 beta 3 and it's working fine. 
However, the issue still persists when importing a repository. So probably, this wasn't included there. 

Cheers!
