### ISSUE TITLE
Placeholder prompt sometimes fails to paste clipping

### ISSUE THREAD

**Issue by aecreations** [aecreations/clippings#233]
Clippings 6.0.6 and 6.1b1+

Steps to repro:
1. Create a clipping with two (2) placeholders. The first one should be a placeholder with multiple values; the second should be a normal placeholder
2. Open a web page in the browser that has a textbox
3. Right-click on the textbox in the web page and select the above clipping from the Clippings submenu
4. In the placeholder prompt that appears, select/enter values then click OK

Result:
Clipping does not get pasted into the textbox. This happens sporadically. Possible explanation: the placeholder prompt window is closed before it has a chance to send a message back to the browser window to perform the placeholder substitution and paste the clipping.

Also, when the placeholder prompt window appears, the following error is displayed in the browser console:
```
 $(...)[0].select is not a function .................... placeholderPrompt.js:99
```
However, this error may not be related to the clipping paste failure.

**Comment by aecreations** [comment]
I've discovered that this isn't anything to do with the placeholder prompt closing before it has a chance to send a response to the browser window. Looking at the debugging log, the cause appears to be that the content script is not responding to the `paste-clipping` message that is sent to it to paste the clipping with placeholders:
```
Clippings/wx: Received message "paste-clipping-with-plchldrs" ... background.js:1744:24
Clippings/wx: Received message "close-placeholder-prmt-dlg" ... background.js:1744:24
Clippings/wx: Extension sending message "paste-clipping" to content script ... background.js:1744:24
Clippings/wx: pasteProcessedClipping(): Failed to paste clipping with placeholders: Error: Could not establish connection. Receiving end does not exist.
```
I'm able to reproduce this a few times. Strangely enough, it doesn't occur when pasting a clipping without any placeholders in its content.

**Comment by aecreations** [comment]
The active tab ID (i.e. the tab where the `paste-clipping` message is going to) is a different value when the paste fails.  I suspect that what's happening is that the placeholder prompt window still has the focus for a very brief time before it closes, and the background script is executing the pasteProcessedClipping() function at the brief moment when the placeholder prompt window is still open. 

This would explain why this issue isn't occurring when pasting a clipping without placeholders.

The only proper solution around this problem is to avoid opening a window when pasting a clipping with placeholders. One possibility is to inject a script into the current web page to display an inline HTML modal dialog on the page, prompting for the placeholder for the clipping to be pasted.

**Comment by aecreations** [comment]
Deferring this issue.

**Comment by aecreations** [comment]
Fixed in 6.1b2. This bug fix is planned to be backported to 6.0.7.

**Comment by LeLake** [comment]
Hi there, odd thing happens with Linux kernel 3.10.0-957.1.3.el7.x86_64:

kernel-3.10.0-327.28.3.el7.x86_64   <--------- Clippings work like a charm
kernel-3.10.0-957.1.3.el7.x86_64   <--------- placeholder issue reappeared

similar behaviour described in this very BUG...
clippings with placeholder don't get pasted into the textbox, but those without the placeholder do get pasted.

Please let me know how I could help with logs or stuff...

Cheers!

**Comment by aecreations** [comment]
What version of Clippings and Firefox are you using?

When this issue occurs, copy any errors that appear in the Browser Console and paste them here.

Also, I would like information on the clipping containing the placeholders when this issue occurs. How many placeholders? Is the first placeholder normal text or has multiple values, the second placeholder, etc.?
