### ISSUE TITLE
Dark mode/reverse contrast UI theme in windows and dialogs

### ISSUE THREAD

**Issue by aecreations** [aecreations/clippings#264]
Add an option to switch to a dark UI theme for all dialog boxes and windows in Clippings so that they blend in with the OS's Dark Mode feature.

**Comment by aecreations** [comment]
The Clippings logo in the welcome page needs to have a lighter-coloured variation for the font so that it is visible in Dark Mode.

**Comment by aecreations** [comment]
Remaining work:
- Tweaks to borders in the Welcome page
- Adjust color of groupbox border in dialogs from the extension preferences page
- Message box dialogs

**Comment by aecreations** [comment]
Also need to fix the following in Dark Mode:
1. Down arrows on drop-down menus
2. Checkmark icon for toggle menu options in Clippings Manager
3. Tweaks to borders in the Welcome page (not started)

**Comment by atomGit** [comment]
i'm not seeing any option to enable the dark theme and it isn't being automatically applied according to the selected browser theme

clippings 6.3.6
firefox 101.*
linux

**Comment by aecreations** [comment]
@atomGit Which Firefox theme are you using?

**Comment by atomGit** [comment]
found the problem - i have `privacy.resistFingerprinting` enabled

i don't want to disable this, so i don't know if there's anything you can do

also i believe Moz intends to enable RFP by default at some point, just so you know
