### ISSUE TITLE
Bring back Clippings Manager redo, a.k.a. "undo undo"

### ISSUE THREAD

**Issue by aecreations** [aecreations/clippings#276]
This is a missing feature from the legacy XUL+XPCOM versions of Clippings. There is a request for this from a review of Clippings on AMO.

**Comment by aecreations** [comment]
Fixed in 6.2

**Comment by Thomas-D-C** [comment]
Is it the ability to redo, after having undone?

**Comment by aecreations** [comment]
Yes. To redo, press the F2 key.

**Comment by Thomas-D-C** [comment]
Sorry, I didn't see this reply before posting on Groups.io. I might have written it differently.


> Yes. To redo, press the F2 key.

Thank you very much. :-)

But, why did you choose `F2` as keyboard shortcut, rather than `Ctrl+Shift+Z`?

**Comment by aecreations** [comment]
Because this is how it was designed. I'll consider adding Ctrl+Shift+Z as an alias in a future release.

**Comment by Thomas-D-C** [comment]
> I'll consider adding Ctrl+Shift+Z as an alias in a future release.

Thank you for the consideration. :-)

I changed my mind slightly. (Please see #523.)
