### ISSUE TITLE
Clippings text module manager can't be brought on top

### ISSUE THREAD

**Issue by rocketsue** [aecreations/clippings#30]
This worked some time ago.

Browser: Firefox ESR 31.5
Clippings Version 4.1.2
OS: Windows 7 Prof.

(sorry for the bad translation of the OS specific terms, my Windows is all German)

* Left click on the Clippings Icon in the Toolbar opens the Clippings Text module manager - but in background.
* I am not able to bring the window into the foreground, so currently it is not possible for me to create new text modules, because:
 * clicking on the window in the aero peek doesn't do anything
 * switching tabs via alt+tab won't work either 
 * closing the manager window by clicking 'x' in the aero peek does work though.
![clippings_text-manager-window](https://cloud.githubusercontent.com/assets/6142295/6735695/33ea36be-ce60-11e4-9768-41d8492fd154.jpg)

I also tried this to access the text module manager in those ways:
* Right click on the Clippings Icon in the Firefox Toolbar. This just shows the Browser's "Adjust..." Dialogue. 
* Enable "show on status bar" in the Clippings settings. This doesn't seem to change anything. Does the status bar in Firefox even exist anymore?

Thank you in advance for shedding light on this subject :)

**Comment by aecreations** [comment]
You say that "this worked some time ago."  Do you remember a change to your system (e.g. new software installed) that might cause this to start happening?

**Comment by rocketsue** [comment]
The corporate PC doesn't allow manual installations, so the only changes made (software-wise) are automatic updates on Firefox, Opera and Adobe Flash Player.

**Comment by aecreations** [comment]
What if the taskbar settings were changed so that it doesn't group multiple windows from a single application into one taskbar button?  Does the problem go away if that setting was changed (right-click on the taskbar, select Properties, then in the Taskbar tab, change the option for the "Taskbar buttons" drop-down menu)?

This is the first time anyone has reported such an issue, so other than that, I'm not sure what else I could suggest.

**Comment by millwood** [comment]
I would suggest that you:

Start the firefox profile manager and create an empty profile.
Start that profile and install clippings.
If it works properly, it is likely one of your add-ons or other customizations is as fault.  You can binary search for the add-on by disabling half of them, then half of the bad set, etc.

As an aside, I've always run with stacked icons and clippings works correctly.

**Comment by rocketsue** [comment]
@aecreations changing the taskbar settings doesn't help. but thank you, I hadn't thought of that.

@millwood Clippings works properly with a fresh profile. On the other hand, disabling all the addons in my current profile doesn't help :( my next task is to look for a way to transfer the history of the Firefox Awesome Bar to another profile, so I can continue working with the new profile - and Clippings.

**Comment by millwood** [comment]
I believe sync will copy history and thus the awesome bar.  So if you sync your old profile and then sync a new empty, you should get most everything transferred.  This includes addons, saved passwords if you like.

**Comment by rocketsue** [comment]
Thank you guys. Very much appreciated :)
