### ISSUE TITLE
two times pasting

### ISSUE THREAD

**Issue by dafidakk** [aecreations/clippings#328]
Hi, clippings has paste text item twice on the text editor

**Comment by aecreations** [comment]
What version of Clippings?
What version of Firefox is it installed into, and which OS are you using?
What is the URL to a website where this issue is occurring?

**Comment by dafidakk** [comment]
Versiyon : 6.2.6
Firefox version : 86.0 (64-bit)
OS : Windows 10 Pro (64-bit)
Last question explains the issue , because this is occurring only our website text editor. Thank you..
