### ISSUE TITLE
Shortcut ctrl + alt + V + Q not works since Clippings 5.0a1

### ISSUE THREAD

**Issue by Endor8** [aecreations/clippings#34]
Hi.
Since Clippings 5.0a1 the shortcut ctrl + alt + v + q not works.
I got only a Beeb, nothing else.  Same behaviour in 5.0a2.
Please take a  look on it.
Thanks.
Endor

**Comment by aecreations** [comment]
Which OS (Windows, Mac) are you experiencing this issue?  Also, what keyboard layout (e.g., English US, German, etc.) are you using?

**Comment by aecreations** [comment]
Also, can you confirm if your other shortcuts work (keys other than "Q")?

**Comment by Endor8** [comment]
I use Windows 7, German keyboard layout and other keys than Q works.

Endor

**Comment by aecreations** [comment]
Commit ae6abe0d87327a423933e4a21ed7ccae933c5623: Added debugging code to log the key code (ASCII) of the key that is pressed.

**Comment by aecreations** [comment]
In Clippings 5.0 beta 1 (released today), I have added debugging messaging that will appear in the browser console (Tools -> Web Developer -> Browser Console in Firefox) when pasting a clipping using its shortcut key.  It will display the character code (ASCII) for the shortcut key that was pressed.  Please install this release, then try inserting a clipping that has the letter 'Q' assigned to it, and observe the message that appears in the browser console.

On my Firefox installation on my MacBook Pro (English-US keyboard, Mac OS X 10.9), the following message appears in the console when I pressed Command+Option+V, and then Q:

> Clippings: Key pressed: "Q"; key code: 81

More info on Clippings 5.0 beta 1: http://aecreations.blogspot.ca/2015/10/clippings-50-beta-1-released-testers.html

**Comment by Endor8** [comment]
Thank you for the new Version.
My mentioned problem is now resolved.
Works fine. But actually only the English locale
could be tested. All other included locales, first needs to be updated.
I updated for me, the German locale, so i was able to
Thank you.
Regards
Endor
