### ISSUE TITLE
The placeholder text field overlaps the buttons on the bottom

### ISSUE THREAD

**Issue by AC-ID** [aecreations/clippings#357]
Firefox 90.0.2 (64-Bit)
Clippings 6.3
Browser/OS language is German

Steps to reproduce:
- Create a clipping with a placeholder
- Open that clipping
- The text field overlaps the buttons on the bottom

![grafik](https://user-images.githubusercontent.com/50912860/128340207-30e806d7-3bf9-433d-8953-021898def979.png)

Let me know if you need any more information.

**Comment by AC-ID** [comment]
It's the same behavior while creating a new clipping:

![grafik](https://user-images.githubusercontent.com/50912860/128473143-be48f00e-5c5d-4c91-9b2b-2683a1b7af8a.png)

**Comment by aecreations** [comment]
I notice in the screen shots that the dialog font sizes are bigger than the window title bar. How were the font sizes adjusted? Were they changed via the browser zoom setting?

**Comment by AC-ID** [comment]
All browser zoom settings are normal (100%) and font is set to the standard (middle).

Nothing else was changed in the browser, but after the update the dialog boxes showed this behavior ...

**Comment by aecreations** [comment]
Can you open a Clippings window or dialog, for example the Neuer Textbaustein/New Clipping dialog, and press CTRL+0 (or equivalent shortcut on German keyboards) to try resetting the zoom level?

If that doesn't work, are there any installed add-ons or themes in Thunderbird that might be causing the default text to be magnified? Maybe try changing the Thunderbird theme to the Default theme?

**Comment by AC-ID** [comment]
Yeah that was strange ...

I already disabled all other addons beforehand to check if they cause the problem.


But you were right, the dialog window had a different zoom level than the rest of the browser.
That caused the problem.

Although all settings are set to default and 100%, when i pressed CTRL+0 the text shrunk and now the dialog is opening in the correct zoom level.


Thanks for the help and sorry for the inconveniences.
