### ISSUE TITLE
Double pasting in youtube live chat comments

### ISSUE THREAD

**Issue by nailfarmer** [aecreations/clippings#401]
Hi, I'm encountering a bug where clippings entries are pasting twice into the comment field on YouTube live chat. The standard YouTube comment input box operates as normal and is only pasted into once as expected.

Clippings: 6.4.1
Firefox: 102.2.0esr Linux

**Comment by aecreations** [comment]
This is caused by not checking that the "contenteditable" attribute on the HTML `<body>` element is set, if the rich text editor is active in an `<iframe>` element.
