### ISSUE TITLE
Clippings issue

### ISSUE THREAD

**Issue by kmacpcr** [aecreations/clippings#406]
Hi Support,

We're using the latest version of Firefox and Clippings - A user has consistently noticed an issue where she posts clippings however it doesn't do it consistently. This is not in igconito mode. A new pofile has been created for the user and clippings removed and reinstalled with the clippings restored afterwards.

Do you have any thoughts on why this would be happening?

Thanks,

Kevin
PCR
3303420981

**Comment by aecreations** [comment]
Is this issue happening on any website, or just on a specific website? Please provide a URL to a web page where this is happening.
