### ISSUE TITLE
Unicode symbols / emojis not supported in placeholders' default values

### ISSUE THREAD

**Issue by nbusseneau** [aecreations/clippings#418]
Reproduction template:
```
$[foo{bar|baz}]
$[quux{←|→}]
$[qux{💪|🚀}]
```
It would be a nice bonus if symbols / emojis were supported in these.

I think you may be already aware considering this snippet [in the docs](https://aecreations.io/clippings/placeholders.php):

> Commonly-used special characters are allowed in default values of placeholders, such as the question mark, parentheses, quotation marks, asterisk, common currency symbols, etc. Note that the pipe symbol (|), curly braces ({}) and square brackets([]) cannot be used.

In any case, thank you for your work and this extension 😄

**Comment by aecreations** [comment]
Unicode table: https://old.unicode-table.com/en/blocks/

**Comment by aecreations** [comment]
Unicode character table: https://old.unicode-table.com/en/blocks/

**Comment by aecreations** [comment]
This will be fixed in Clippings 6.5 and Clippings for Thunderbird 6.3.

**Comment by nbusseneau** [comment]
Cheers, thanks.
