### ISSUE TITLE
Clippings not working on Thunderbird 44.0a2 (Earlybird)

### ISSUE THREAD

**Issue by aecreations** [aecreations/clippings#43]
The error console reports this error when the message compose window is opened:

> Error: SyntaxError: missing ; before statement
> Source File: chrome://clippings/content/tbMsgComposeOverlay.js
> Line: 667, Column: 22

Which is due to this offending JavaScript statement:

> let (that = this) {

Which is no longer supported as of version 44 (explanation here: https://blog.mozilla.org/addons/2015/10/14/breaking-changes-let-const-firefox-nightly-44/)

This is related to issue #42.

**Comment by nolovelust** [comment]
downloaded and installed b2 from https://addons.mozilla.org/firefox/downloads/latest-beta/1347/addon-1347-latest.xpi?src=search but still not working

**Comment by aecreations** [comment]
This fix was made *after* 5.0 beta 2 was released, so of course it won't be working in beta 2.  The fix will be included in an upcoming release.  If the fix is needed urgently, then download the source from the repository and build it yourself.

**Comment by nolovelust** [comment]
Sorry, I thought it was relesed

**Comment by aecreations** [comment]
Fixed in Clippings 5.0
