### ISSUE TITLE
Publish to Chrome Web Store - for Google Chrome

### ISSUE THREAD

**Issue by vitaly-zdanevich** [aecreations/clippings#439]

**Comment by aecreations** [comment]
There are no plans to make Clippings compatible with Google Chrome.

**Comment by vitaly-zdanevich** [comment]
But both Firefox and Google Chrome uses the same API - WebExtensions API?

**Comment by aecreations** [comment]
There are differences in the WebExtension APIs between the two browsers. Clippings uses APIs that are either incompatible or missing in Chrome.

As stated above, there are no plans to make Clippings compatible with Google Chrome.

**Comment by vitaly-zdanevich** [comment]
Do you know similar extension for Chrome?
