### ISSUE TITLE
Pasting clipping with placeholders not working on Linux

### ISSUE THREAD

**Issue by aecreations** [aecreations/clippings#463]
Reported from the forums:

> When I updated to the last version (6.5.6) I noticed placeholders are no longer working properly.
> 
> My templates without placeholders work fine - I select the clipping and it pastes into the active window.
> 
> For templates with placeholders, the dialog pops up with the fields to fill in, and after selecting "OK" nothing happens.  Nothing is pasted, and nothing is in the paste buffer.
> 
> I'm running Ubuntu 20.04.5 LTS, with Firefox 126.0.1
> 
> Reverting to version 6.5.5 makes everything work again.

**Comment by aecreations** [comment]
Issue is confirmed with Clippings 6.5.6 on Firefox 127.0.  This issue is NOT occurring on Firefox 115 ESR.

**Comment by aecreations** [comment]
Bug fix failed. Need to revert to old pasting behaviour, where the paste message sent to the content script is called from a function that is invoked after a short timeout. This only needs to be done on Linux.

Also observed: the call to `browser.windows.update()` on the browser window seems to have no effect on Linux, and it does not throw an error.

**Comment by aecreations** [comment]
Confirmed fixed. Tested on Ubuntu 22.04 and Firefox 127. Also regression tested on Windows and macOS, with the browser window in normal size and full screen.

**Comment by slrtbtfs** [comment]
Tested on OpenSUSE 15.5 with Firefox 115.11.0esr (64-Bit). There, Clippings was not pasting anything anymore presumably since the upgrade to Clippings 6.5.6, but with Clippings 6.5.6.1 beta 2 it works again.

**Comment by aecreations** [comment]
Confirmed that issue is reproducible beginning in Firefox 121.

**Comment by aecreations** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1905471
