### ISSUE TITLE
Cannot export / import clippings from Firefox 42.0 to Firefox 38.4 ESR

### ISSUE THREAD

**Issue by sherylnus** [aecreations/clippings#54]
I am trying to export my near 1000 clippings from my old laptop which was running Firefox 42.0 (after an update - was 38.4.ESR) but it either creates a Partial file of appr 308MB (instead of the full file 931MB), or doent do anything at all - (If I try HTML format).

When I try to import an existing backup file or any of the export files into Firefox 38.4, I get a messages stating the file may be invalid: "The selected file may not be a valid Clippings file."
Both clippings add-on versions are identical: "4.1.2.1-signed".
Both laptops are running Windows 7 but have different user account names.  I checked the access to the files though, and they are ok.

Any ideas are greatly appreciated.  I've tried everything!
Thanks

**Comment by aecreations** [comment]
A workaround for such a large data source file would be to copy the data source RDF file (named "clipdat2.rdf" from the data source location on your old laptop (with Firefox 42) to the data source location where you have Firefox 38 ESR installed.

Make sure Firefox is not running when doing this copy.  Note that following this method will overwrite the RDF file in the destination data source location, unless you move it somewhere else.

See the Clippings FAQ for how to locate the data source location.

**Comment by sherylnus** [comment]
Thank you for the feedback on this issue.  I've done this already but I had
Firefox running at the time.  I will try it again with Firefox off.

Thanks,
Sheryl

On Thu, Dec 10, 2015 at 1:10 AM, aecreations <notifications@github.com>
wrote:

> A workaround for such a large data source file would be to copy the data
> source RDF file (named "clipdat2.rdf" from the data source location on your
> old laptop (with Firefox 42) to the data source location where you have
> Firefox 38 ESR installed.
>
> Make sure Firefox is not running when doing this copy. Note that following
> this method will overwrite the RDF file in the destination data source
> location, unless you move it somewhere else.
>
> See the Clippings FAQ for how to locate the data source location.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aecreations/clippings/issues/54#issuecomment-163509297>
> .
>



-- 
Best Regards,
Sheryl Haase

**Comment by sherylnus** [comment]
Actually I just tried it again with Firefox closed on both servers and I
was able to get the clippings to the new laptop!  I didnt realize all I had
to do was to copy it from one laptop to the other.  I was always trying to
export and import or restore the backup.  This was much simpler than
expected.

Thank you so much for the suggestion!
Sherylnus

On Thu, Dec 10, 2015 at 1:10 AM, aecreations <notifications@github.com>
wrote:

> A workaround for such a large data source file would be to copy the data
> source RDF file (named "clipdat2.rdf" from the data source location on your
> old laptop (with Firefox 42) to the data source location where you have
> Firefox 38 ESR installed.
>
> Make sure Firefox is not running when doing this copy. Note that following
> this method will overwrite the RDF file in the destination data source
> location, unless you move it somewhere else.
>
> See the Clippings FAQ for how to locate the data source location.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aecreations/clippings/issues/54#issuecomment-163509297>
> .
>



-- 
Best Regards,
Sheryl Haase
