### ISSUE TITLE
Special characters in placeholder default value causes the placeholder to be pasted as is, without any prompts

### ISSUE THREAD

**Issue by aecreations** [aecreations/clippings#73]
Example:

$[Close{I hope this is ok?}]

The presence of the question mark seems to cause the placeholder prompt to not appear when pasting a clipping containing this.  Not yet confirmed if other special characters are affected.

**Comment by aecreations** [comment]
The same behaviour is seen for most special characters... /\$:;"'!@%<>^&* and #

**Comment by Kasper05** [comment]
Is this still being applied in one of upcoming releases?

**Comment by kodicd** [comment]
Still seeing this problem - is there a solution nearby? Thx!

**Comment by aecreations** [comment]
This commit from the `clippings-tb` repo can be ported over unmodified: https://github.com/aecreations/clippings-tb/commit/16fe0548f183358dcb22036654c7a2c08a6fc4a7

**Comment by Kasper05** [comment]
And also add the characters ( )

**Comment by aecreations** [comment]
Need to fix a regression issue where if a placeholder is used multiple times in the same clipping, only the first occurrence is replaced.

**Comment by aecreations** [comment]
Fixed in 6.1.5
